// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "license": {
            "name": "MIT",
            "url": "https://mit-license.org/"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/device": {
            "get": {
                "description": "Get DeviceInfo about all devices",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "device requiresAuth requiresAdmin"
                ],
                "summary": "Get all devices",
                "parameters": [
                    {
                        "maximum": 20,
                        "type": "integer",
                        "default": 20,
                        "description": "Amount of devices to return",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "minimum": 0,
                        "type": "integer",
                        "default": 0,
                        "description": "How much devices to skip before starting to return devices",
                        "name": "offset",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Only return devices with this lease status",
                        "name": "leased",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/apiResponses.BaseResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/handlers.DeviceInfo"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/apiResponses.UnauthorizedError"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/apiResponses.ForbiddenError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/apiResponses.InternalServerError"
                        }
                    }
                }
            }
        },
        "/device/register": {
            "post": {
                "description": "Register a new device using the registration pin",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "device requiresAuth requiresAdmin"
                ],
                "summary": "Register a new device",
                "parameters": [
                    {
                        "description": "Registration pin\n` + "`" + `pin` + "`" + `: 4 digit registration pin recieved by the device via websocket API",
                        "name": "registration_data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.PostDeviceRegisterBody"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/apiResponses.BaseResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/handlers.PostDeviceRegisterResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/apiResponses.NotFoundError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/apiResponses.InternalServerError"
                        }
                    }
                }
            }
        },
        "/device/relink": {
            "post": {
                "description": "Relink a device using the registration pin. WARNING: This will generate a new auth token for the device.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "device requiresAuth requiresAdmin"
                ],
                "summary": "Relink a device to an old database entry",
                "parameters": [
                    {
                        "description": "Registration pin and device ID\n` + "`" + `pin` + "`" + `: 4 digit registration pin recieved by the device via websocket API",
                        "name": "registration_data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.PostDeviceRelinkBody"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/apiResponses.BaseResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/handlers.PostDeviceRegisterResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/apiResponses.NotFoundError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/apiResponses.InternalServerError"
                        }
                    }
                }
            }
        },
        "/device/{id}": {
            "get": {
                "description": "Get info about a device by using its id or room",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "device requiresAuth requiresAdmin"
                ],
                "summary": "Get device by id",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Device ID or Room",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "enum": [
                            "\"id\"",
                            "\"room\""
                        ],
                        "type": "string",
                        "default": "\"id\"",
                        "description": "Specify identifier type",
                        "name": "type",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/apiResponses.BaseResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/handlers.DeviceInfo"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/apiResponses.UnauthorizedError"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/apiResponses.ForbiddenError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/apiResponses.NotFoundError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/apiResponses.InternalServerError"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete a device from the database by using its id or room. The websocket connection, if present, will also be terminated.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "device requiresAuth requiresAdmin"
                ],
                "summary": "Delete device by id",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Device ID or Room",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "enum": [
                            "\"id\"",
                            "\"room\""
                        ],
                        "type": "string",
                        "default": "\"id\"",
                        "description": "Specify identifier type",
                        "name": "type",
                        "in": "query"
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content",
                        "schema": {
                            "$ref": "#/definitions/apiResponses.BaseBase"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/apiResponses.UnauthorizedError"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/apiResponses.ForbiddenError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/apiResponses.NotFoundError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/apiResponses.InternalServerError"
                        }
                    }
                }
            }
        },
        "/login": {
            "get": {
                "description": "Redirect to the google OAuth endpoint",
                "tags": [
                    "auth"
                ],
                "summary": "Login with google OAuth",
                "responses": {
                    "302": {
                        "description": "Found"
                    }
                }
            }
        },
        "/logout": {
            "get": {
                "description": "Invalidate the session token",
                "tags": [
                    "auth requiresAuth"
                ],
                "summary": "Logout",
                "responses": {
                    "302": {
                        "description": "Found"
                    }
                }
            }
        },
        "/me": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user requiresAuth"
                ],
                "summary": "Get UserInfo about current authenticated user",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/apiResponses.BaseResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/handlers.UserInfo"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/apiResponses.UnauthorizedError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/apiResponses.InternalServerError"
                        }
                    }
                }
            }
        },
        "/oauth2callback": {
            "get": {
                "description": "The callback url for google OAuth that processes the things. Can not be used indivualy (requires google OAuth code)\nRefer too google OAuth docs for more information.",
                "tags": [
                    "auth"
                ],
                "summary": "Callback url for google OAuth",
                "responses": {
                    "302": {
                        "description": "Found"
                    }
                }
            }
        },
        "/session": {
            "get": {
                "description": "Get all sessions owned by the current user or for all users if acting as admin",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "session requiresAuth supportsAdmin"
                ],
                "summary": "Get sessions owned by the current user or all users",
                "parameters": [
                    {
                        "enum": [
                            0,
                            1
                        ],
                        "type": "integer",
                        "default": 0,
                        "description": "Try to act as this role (will cause 403 if you do not have this role)",
                        "name": "asRole",
                        "in": "query"
                    },
                    {
                        "maximum": 20,
                        "type": "integer",
                        "default": 20,
                        "description": "Amount of sessions to return",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "minimum": 0,
                        "type": "integer",
                        "default": 0,
                        "description": "How much sessions to skip before starting to return sessions",
                        "name": "offset",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Only return sessions that use this question",
                        "name": "questionID",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/apiResponses.BaseResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/handlers.SessionInfo"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/apiResponses.UnauthorizedError"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/apiResponses.ForbiddenError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/apiResponses.InternalServerError"
                        }
                    }
                }
            },
            "post": {
                "description": "Any user can POST this endpoint to start a session if they dont have an active session",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "session requiresAuth"
                ],
                "summary": "Start a new session if no active one is present",
                "parameters": [
                    {
                        "description": "device id and question to use for the session\n` + "`" + `device_id` + "`" + `: Id of the device to start the session on.\n` + "`" + `question` + "`" + `: Question to start the session id with. If identical question already exists in the database, it is used. If it doesnt exist a new entry is created.",
                        "name": "session_info",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.PostSessionBody"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/apiResponses.BaseResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/handlers.SessionInfo"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/apiResponses.BadRequestError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/apiResponses.UnauthorizedError"
                        }
                    },
                    "409": {
                        "description": "User already has an active session",
                        "schema": {
                            "$ref": "#/definitions/apiResponses.ConflictError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/apiResponses.InternalServerError"
                        }
                    },
                    "503": {
                        "description": "Requested device is not available",
                        "schema": {
                            "$ref": "#/definitions/apiResponses.ServiceUnavailableError"
                        }
                    }
                }
            }
        },
        "/session/current": {
            "get": {
                "description": "Any user can query this endpoint for their own session",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "session requiresAuth supportsAdmin"
                ],
                "summary": "Get your current session",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/apiResponses.BaseResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/handlers.SessionInfo"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/apiResponses.UnauthorizedError"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/apiResponses.ForbiddenError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/apiResponses.NotFoundError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/apiResponses.InternalServerError"
                        }
                    }
                }
            }
        },
        "/session/stop": {
            "post": {
                "description": "Any user can POST this endpoint to stop their own session.\nMight be moved to PATCH ` + "`" + `/session` + "`" + `",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "session requiresAuth"
                ],
                "summary": "Stop your own sesssion",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/apiResponses.BaseResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/handlers.SessionInfo"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "404": {
                        "description": "no current session",
                        "schema": {
                            "$ref": "#/definitions/apiResponses.NotFoundError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/apiResponses.InternalServerError"
                        }
                    }
                }
            }
        },
        "/session/{id}": {
            "get": {
                "description": "Any user can query this endpoint for their own sessions\nPrivileged users can add ` + "`" + `asRole=1` + "`" + ` query parameter to act with their privileges",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "session requiresAuth supportsAdmin"
                ],
                "summary": "Get sessions by id if owner or acting as admin",
                "parameters": [
                    {
                        "enum": [
                            0,
                            1
                        ],
                        "type": "integer",
                        "default": 0,
                        "description": "Try to act as this role (will cause 403 if you do not have this role)",
                        "name": "asRole",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Id of the session",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/apiResponses.BaseResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/handlers.SessionInfo"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/apiResponses.UnauthorizedError"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/apiResponses.ForbiddenError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/apiResponses.NotFoundError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/apiResponses.InternalServerError"
                        }
                    }
                }
            }
        },
        "/session/{id}/stop": {
            "post": {
                "description": "Admins can POST this endpoint to stop any session\nMight be moved to PATCH ` + "`" + `/session/{id}` + "`" + `",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "session requiresAuth requiresAdmin"
                ],
                "summary": "Stop a session with specific id",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Session id of the session to stop",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/apiResponses.BaseResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/handlers.SessionInfo"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/apiResponses.UnauthorizedError"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/apiResponses.ForbiddenError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/apiResponses.NotFoundError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/apiResponses.InternalServerError"
                        }
                    }
                }
            }
        },
        "/user": {
            "get": {
                "description": "Get UserInfo about all users",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user requiresAuth requiresAdmin"
                ],
                "summary": "Get all users",
                "parameters": [
                    {
                        "maximum": 20,
                        "type": "integer",
                        "default": 20,
                        "description": "Amount of users to return",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "minimum": 0,
                        "type": "integer",
                        "default": 0,
                        "description": "How much users to skip before starting to return users",
                        "name": "offset",
                        "in": "query"
                    },
                    {
                        "enum": [
                            0,
                            1
                        ],
                        "type": "integer",
                        "description": "Only return users with this role",
                        "name": "role",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/apiResponses.BaseResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/handlers.UserInfo"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/apiResponses.UnauthorizedError"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/apiResponses.ForbiddenError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/apiResponses.InternalServerError"
                        }
                    }
                }
            }
        },
        "/user/{id}": {
            "get": {
                "description": "Get info about a user by using either their id or email",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user requiresAuth requiresAdmin"
                ],
                "summary": "Get user by id",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID or email",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "enum": [
                            "\"id\"",
                            "\"email\""
                        ],
                        "type": "string",
                        "default": "\"id\"",
                        "description": "Specify identifier type",
                        "name": "type",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/apiResponses.BaseResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/handlers.UserInfo"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/apiResponses.UnauthorizedError"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/apiResponses.ForbiddenError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/apiResponses.NotFoundError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/apiResponses.InternalServerError"
                        }
                    }
                }
            }
        },
        "/user/{id}/pfp": {
            "get": {
                "description": "Get a users profile picture by using either their id or email if authenticated as the user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json",
                    "image/jpeg"
                ],
                "tags": [
                    "user requiresAuth"
                ],
                "summary": "Get user pfp by id",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID or email",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "enum": [
                            "\"id\"",
                            "\"email\""
                        ],
                        "type": "string",
                        "default": "\"id\"",
                        "description": "Specify identifier type",
                        "name": "type",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "file"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/apiResponses.UnauthorizedError"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/apiResponses.ForbiddenError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/apiResponses.NotFoundError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/apiResponses.InternalServerError"
                        }
                    }
                }
            }
        },
        "/v": {
            "get": {
                "description": "Get current api name, version and deployment env (prod, dev)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "version"
                ],
                "summary": "Get the api version",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/apiResponses.BaseResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/handlers.GetVersionSuccessResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/ws": {
            "get": {
                "description": "Open a websocket connection used by devices to communicate with the server.\nDevices get notified about session changes and send votes via this connection.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "device_websocket"
                ],
                "summary": "Open a connection to the device websocket API",
                "responses": {
                    "101": {
                        "description": "Switching Protocols (WebSocket Upgrade)",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "apiResponses.BadRequestError": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "Could not parse 'hi' as int"
                },
                "status": {
                    "type": "integer",
                    "default": 400
                },
                "success": {
                    "type": "boolean",
                    "default": false
                },
                "timestamp": {
                    "type": "string",
                    "format": "date-time",
                    "example": "2026-01-12T21:52:50.253429709+01:00"
                }
            }
        },
        "apiResponses.BaseBase": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "Ok"
                },
                "status": {
                    "type": "integer",
                    "example": 200
                },
                "success": {
                    "type": "boolean",
                    "example": true
                },
                "timestamp": {
                    "type": "string",
                    "format": "date-time",
                    "example": "2026-01-12T21:52:50.253429709+01:00"
                }
            }
        },
        "apiResponses.BaseResponse": {
            "type": "object",
            "properties": {
                "data": {},
                "message": {
                    "type": "string",
                    "example": "Ok"
                },
                "status": {
                    "type": "integer",
                    "example": 200
                },
                "success": {
                    "type": "boolean",
                    "example": true
                },
                "timestamp": {
                    "type": "string",
                    "format": "date-time",
                    "example": "2026-01-12T21:52:50.253429709+01:00"
                }
            }
        },
        "apiResponses.ConflictError": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "default": "Conflict"
                },
                "status": {
                    "type": "integer",
                    "default": 409
                },
                "success": {
                    "type": "boolean",
                    "default": false
                },
                "timestamp": {
                    "type": "string",
                    "format": "date-time",
                    "example": "2026-01-12T21:52:50.253429709+01:00"
                }
            }
        },
        "apiResponses.ForbiddenError": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "default": "Forbidden"
                },
                "status": {
                    "type": "integer",
                    "default": 403
                },
                "success": {
                    "type": "boolean",
                    "default": false
                },
                "timestamp": {
                    "type": "string",
                    "format": "date-time",
                    "example": "2026-01-12T21:52:50.253429709+01:00"
                }
            }
        },
        "apiResponses.InternalServerError": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "default": "Internal Server Error"
                },
                "status": {
                    "type": "integer",
                    "default": 500
                },
                "success": {
                    "type": "boolean",
                    "default": false
                },
                "timestamp": {
                    "type": "string",
                    "format": "date-time",
                    "example": "2026-01-12T21:52:50.253429709+01:00"
                }
            }
        },
        "apiResponses.NotFoundError": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "default": "Not Found"
                },
                "status": {
                    "type": "integer",
                    "default": 404
                },
                "success": {
                    "type": "boolean",
                    "default": false
                },
                "timestamp": {
                    "type": "string",
                    "format": "date-time",
                    "example": "2026-01-12T21:52:50.253429709+01:00"
                }
            }
        },
        "apiResponses.ServiceUnavailableError": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "default": "Service Unavailable"
                },
                "status": {
                    "type": "integer",
                    "default": 503
                },
                "success": {
                    "type": "boolean",
                    "default": false
                },
                "timestamp": {
                    "type": "string",
                    "format": "date-time",
                    "example": "2026-01-12T21:52:50.253429709+01:00"
                }
            }
        },
        "apiResponses.UnauthorizedError": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "Invalid or expired session"
                },
                "status": {
                    "type": "integer",
                    "default": 401
                },
                "success": {
                    "type": "boolean",
                    "default": false
                },
                "timestamp": {
                    "type": "string",
                    "format": "date-time",
                    "example": "2026-01-12T21:52:50.253429709+01:00"
                }
            }
        },
        "handlers.DeviceInfo": {
            "type": "object",
            "properties": {
                "active_session_id": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "last_seen": {
                    "type": "string"
                },
                "latest_login": {
                    "type": "string"
                },
                "lease_start": {
                    "type": "string"
                },
                "registration_date": {
                    "type": "string"
                },
                "room": {
                    "type": "string"
                }
            }
        },
        "handlers.GetVersionSuccessResponse": {
            "type": "object",
            "properties": {
                "environment": {
                    "type": "string",
                    "example": "development"
                },
                "name": {
                    "type": "string",
                    "example": "schoolbox-backend"
                },
                "version": {
                    "type": "string",
                    "example": "1.0.0"
                }
            }
        },
        "handlers.PostDeviceRegisterBody": {
            "type": "object",
            "properties": {
                "pin": {
                    "type": "integer"
                }
            }
        },
        "handlers.PostDeviceRegisterResponse": {
            "type": "object",
            "properties": {
                "device_id": {
                    "type": "integer"
                }
            }
        },
        "handlers.PostDeviceRelinkBody": {
            "type": "object",
            "properties": {
                "device_id": {
                    "type": "integer"
                },
                "pin": {
                    "type": "integer"
                }
            }
        },
        "handlers.PostSessionBody": {
            "type": "object",
            "properties": {
                "device_id": {
                    "description": "@Description",
                    "type": "integer"
                },
                "question": {
                    "description": "@Description",
                    "type": "string"
                }
            }
        },
        "handlers.SessionInfo": {
            "type": "object",
            "properties": {
                "date": {
                    "type": "string",
                    "format": "date-time"
                },
                "device_id": {
                    "type": "integer"
                },
                "first_answer_time": {
                    "type": "string",
                    "format": "date-time"
                },
                "id": {
                    "type": "integer"
                },
                "last_answer_time": {
                    "type": "string",
                    "format": "date-time"
                },
                "question": {
                    "type": "string"
                },
                "question_id": {
                    "type": "integer"
                },
                "stopped_at": {
                    "type": "string",
                    "format": "date-time"
                },
                "user_id": {
                    "type": "integer"
                },
                "votes": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                }
            }
        },
        "handlers.UserInfo": {
            "type": "object",
            "properties": {
                "default_question": {
                    "type": "string"
                },
                "display_name": {
                    "type": "string"
                },
                "email": {
                    "type": "string",
                    "format": "email"
                },
                "google_sub": {
                    "type": "string",
                    "example": "012345678901234567890"
                },
                "id": {
                    "type": "integer"
                },
                "joinedAt": {
                    "type": "string",
                    "format": "date-time"
                },
                "name": {
                    "type": "string",
                    "format": "name"
                },
                "picture_url": {
                    "type": "string",
                    "format": "url"
                },
                "role": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0.0",
	Host:             "localhost:8000",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "Schoolbox API",
	Description:      "The API for Schoolbox.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
