package api

import (
	"net/http"
	"os"

	"github.com/MonkyMars/gecho"
	"gorm.io/gorm"

	"github.com/CLDWare/schoolbox-backend/config"
	"github.com/CLDWare/schoolbox-backend/internal/handlers"
	"github.com/CLDWare/schoolbox-backend/internal/middleware"

	_ "github.com/CLDWare/schoolbox-backend/docs" // docs is generated by Swag CLI, you have to import it.
	httpSwagger "github.com/swaggo/http-swagger/v2"
)

//	@title			Schoolbox API
//	@version		1.0.0
//	@description	The API for Schoolbox.

//	@license.name	MIT
//	@license.url	https://mit-license.org/

//	@host		localhost:8000
//	@BasePath	/api

// API holds the API dependencies
type API struct {
	config                *config.Config
	database              *gorm.DB
	versionHandler        *handlers.VersionHandler
	websocketHandler      *handlers.WebsocketHandler
	authenticationHandler *handlers.AuthenticationHandler
	UserHandler           *handlers.UserHandler
	SessionHandler        *handlers.SessionHandler
	DeviceHandler         *handlers.DeviceHandler
}

// NewAPI creates a new API instance
func NewAPI(db *gorm.DB, quitCh chan os.Signal) *API {
	cfg := config.Get()
	websocketHandler := handlers.NewWebsocketHandler(cfg, db)
	return &API{
		config:                cfg,
		database:              db,
		versionHandler:        handlers.NewVersionHandler(quitCh, cfg),
		websocketHandler:      websocketHandler,
		authenticationHandler: handlers.NewAuthenticationHandler(quitCh, cfg, db),
		UserHandler:           handlers.NewUserHandler(quitCh, cfg, db),
		SessionHandler:        handlers.NewSessionHandler(quitCh, cfg, db, websocketHandler),
		DeviceHandler:         handlers.NewDeviceHandler(quitCh, cfg, db, websocketHandler),
	}
}

func NewMethodRouter(handlerFuncMap map[string]http.HandlerFunc) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		if handlerFuncMap[r.Method] != nil {
			handlerFuncMap[r.Method](w, r)
		} else {
			gecho.MethodNotAllowed(w).Send()
		}
	}
}

// CreateMux creates and configures the HTTP mux
func (api *API) CreateMux() *http.ServeMux {
	mux := http.NewServeMux()
	api.setupRoutes(mux)
	return mux
}

// setupRoutes configures all the routes.
func (api *API) setupRoutes(mux *http.ServeMux) {
	// Version route
	mux.HandleFunc("/v", api.versionHandler.GetVersion)

	// Websocket connection
	mux.HandleFunc("/ws", api.websocketHandler.InitialiseWebsocket)

	// authentication middleware
	auth := middleware.NewAuthenticationMiddleware(api.config, api.database)

	// Frontend authentication
	mux.HandleFunc("/login", api.authenticationHandler.GetLogin)                  // redirect to google OAuth consent
	mux.HandleFunc("/oauth2callback", api.authenticationHandler.GetOAuthCallback) // google OAuth consent callback
	mux.HandleFunc("/logout", auth.Required(api.authenticationHandler.GetLogout))

	// User api
	mux.HandleFunc("/me", auth.Required(api.UserHandler.GetMe))
	mux.HandleFunc("/user", auth.RequiresAdmin(api.UserHandler.GetUser))
	mux.HandleFunc("/user/{id}", auth.RequiresAdmin(api.UserHandler.GetUserById))
	mux.HandleFunc("/user/{id}/pfp", auth.Required(api.UserHandler.GetUserPfpById))

	// Device api
	mux.HandleFunc("/device", auth.RequiresAdmin(api.DeviceHandler.GetDevice))
	deviceByIdRouter := NewMethodRouter(map[string]http.HandlerFunc{
		http.MethodGet:    api.DeviceHandler.GetDeviceById,
		http.MethodDelete: api.DeviceHandler.DeleteDeviceById,
	})
	mux.HandleFunc("/device/{id}", auth.RequiresAdmin(deviceByIdRouter))

	mux.HandleFunc("/device/register", auth.RequiresAdmin(api.DeviceHandler.PostDeviceRegister))
	mux.HandleFunc("/device/relink", auth.RequiresAdmin(api.DeviceHandler.PostDeviceRelink))

	// Session api
	sessionRouter := NewMethodRouter(map[string]http.HandlerFunc{
		http.MethodGet:  api.SessionHandler.GetSession,
		http.MethodPost: api.SessionHandler.PostSession,
	})
	mux.HandleFunc("/session", auth.Required(sessionRouter))
	mux.HandleFunc("/session/stop", auth.Required(api.SessionHandler.PostSessionStop))
	mux.HandleFunc("/session/current", auth.Required(api.SessionHandler.GetCurrentSession))
	mux.HandleFunc("/session/{id}", auth.Required(api.SessionHandler.GetSessionById))
	mux.HandleFunc("/session/{id}/stop", auth.RequiresAdmin(api.SessionHandler.PostSessionStopById))

	// Swagger API docs
	mux.Handle("/swagger/", http.StripPrefix("/swagger/",
		http.HandlerFunc(
			httpSwagger.Handler(
				httpSwagger.URL("http://localhost:8000/api/swagger/doc.json"), //The url pointing to API definition
			),
		),
	))

	// Fallback route - must be last because it matches all routes.
	mux.HandleFunc("/", fallBack)
}

// ApplyMiddleware applies middleware to a handler
func ApplyMiddleware(handler http.Handler) http.Handler {
	return middleware.LoggingMiddleware(
		middleware.CORSMiddleware(handler),
	)
}

func fallBack(w http.ResponseWriter, r *http.Request) {
	gecho.NotFound(w).Send()
}
